apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gsast.fullname" . }}-worker
  labels:
    {{- include "gsast.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      component: gsast-worker
  replicas: {{ .Values.worker.replicaCount | default 1 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      {{- if .Values.internal.enabled }}
      {{- if .Values.internal.podAnnotations }}
      annotations:
        {{- toYaml .Values.internal.podAnnotations | nindent 8 }}
      {{- end }}
      {{- end }}
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: gsast-worker
    spec:
      {{- include "gsast.caVolumes" . | nindent 6 }}
      containers:
        - name: worker
          image: {{ .Values.image.repository | default .Values.worker.image.repositoryPrefix }}:{{ .Values.image.tag | default .Values.worker.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.worker.image.pullPolicy }}
          command: [ "python3", "/app/gsast/worker.py" ]
          env:
            {{- include "gsast.commonEnv" . | nindent 12 }}
            {{- include "gsast.caVolumeMounts" . | nindent 12 }}
            {{- if .Values.environment.customGitlabCA.enabled }}
            - name: GIT_SSL_CAINFO
              value: {{ .Values.environment.customGitlabCA.caMountPath }}{{ .Values.environment.customGitlabCA.caFile }}
            {{- end }}
          {{- if .Values.environment.customGitlabCA.enabled }}
          volumeMounts:
          - name: custom-gitlab-ca
            mountPath: {{ .Values.environment.customGitlabCA.caMountPath }}
          {{- end }}
          resources:
            {{- if .Values.worker.resources }}
            {{- toYaml .Values.worker.resources | nindent 12 }}
            {{- else }}
            limits:
              cpu: 3000m
              memory: 6000Mi
            {{- end }}
      terminationGracePeriodSeconds: 120