# Open-source configuration
# This setup includes a Redis instance and takes secrets from environment variables

# Global image configuration (can be overridden per component)
image:
  repository: "gsast"
  tag: "latest"
  pullPolicy: IfNotPresent

# Redis configuration - embedded Redis for OSS setup
redis:
  enabled: true
  auth:
    enabled: true
  master:
    persistence:
      enabled: false
  replica:
    replicaCount: 0

# No external secret for OSS setup - secrets come from environment
existingSecret: null

# Environment configuration
environment:
  # Proxy settings - set via environment variables if needed
  httpProxy: null
  httpsProxy: null
  noProxy: null
  
  # Custom GitLab CA configuration
  customGitlabCA:
    enabled: false
    configMapName: gsast-ca
    caMountPath: /ca/
    caFile: gitlab_ca.crt

# API configuration
api:
  replicaCount: 1
  host: null
  loadBalancerIP: null
  
  # Service configuration
  service:
    type: ClusterIP
    port: 5000
    
  # Ingress configuration (disabled by default)
  ingress:
    enabled: false
    # className: nginx
    # hosts:
    #   - host: gsast.example.com
    #     paths:
    #       - path: /
    #         pathType: Prefix
  
  # Resource limits
  resources:
    limits:
      cpu: 1500m
      memory: 2500Mi

# Worker configuration
worker:
  replicaCount: 1
  
  # Image configuration (falls back to global image if not specified)
  image:
    repositoryPrefix: null  # Uses global image.repository
    tag: null              # Uses global image.tag
    pullPolicy: null       # Uses global image.pullPolicy
  
  # HPA configuration
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
  
  # Resource limits
  resources:
    requests:
      cpu: 100m      # Start small, scale up based on actual usage
      memory: 500Mi  # Reasonable starting point
    limits:
      cpu: 3000m
      memory: 6000Mi

# Internal setup disabled for OSS deployment
internal:
  enabled: false
  # Pod annotations for internal deployments
  podAnnotations: {}
  # Service annotations for internal deployments
  serviceAnnotations: {}
  # Additional annotations
  annotations: {}
  # Additional labels
  labels: {}

# Secrets configuration - override these values during deployment
# For security, override via: helm install --set secrets.apiSecretKey=xxx
# Or use external secret management with existingSecret
secrets:
  apiSecretKey: "change-me-secret-key"
  githubToken: "change-me-github-token"
  gitlabUrl: "https://gitlab.example.com"
  gitlabApiToken: "change-me-gitlab-token"
  # Complete Redis URL with auth - only used when redis.enabled=false
  # For external Redis, provide the complete URI: redis://:password@host:port
  redisUrl: "redis://:password@external-redis:6379"